// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_clinica.Persistence;

#nullable disable

namespace backend_clinica.Persistence.Migrations
{
    [DbContext(typeof(ClinicalDbContext))]
    partial class ClinicalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend_clinica.Persistence.Entities.CartaConcentimientoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("RutaArchivo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("cartas_concentimiento", (string)null);
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.ComentarioEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("comentarios", (string)null);
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.ComentarioSesionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AspectoAMedir")
                        .HasColumnType("text");

                    b.Property<int>("NumeroSesion")
                        .HasColumnType("integer");

                    b.Property<long>("SesionId")
                        .HasColumnType("bigint");

                    b.Property<byte>("ValoracionFin")
                        .HasColumnType("smallint");

                    b.Property<byte>("ValoracionInicio")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("SesionId");

                    b.ToTable("comentarios_sesion", (string)null);
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.EmpleadoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Contrasenia")
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Usuario")
                        .HasColumnType("text");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("empleados", (string)null);

                    b.HasDiscriminator<string>("rol").HasValue("empleado");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.Examen1Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("PuntuacionArregloPersonal")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionArticulacion")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionBienestar")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionCoherencia")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionContactoVisual")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionEspontaneidad")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionHabla")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionPostura")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionVelocidadHabla")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionVestimenta")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionVolumenHabla")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("examenes_1", (string)null);
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.ExpedienteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Antecedentes")
                        .HasColumnType("text");

                    b.Property<string>("Deseo")
                        .HasColumnType("text");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("text");

                    b.Property<string>("EnfermedadPrevia")
                        .HasColumnType("text");

                    b.Property<string>("Medicamentos")
                        .HasColumnType("text");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("text");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("PreguntaMagica")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("expedientes", (string)null);
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.FamiliarConfianzaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExpedienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Parentesco")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("familiares_confianza", (string)null);
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.InstrumentoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("NombreInstrumento")
                        .HasColumnType("text");

                    b.Property<long>("PsicologoId")
                        .HasColumnType("bigint");

                    b.Property<string>("RutaArchivo")
                        .HasColumnType("text");

                    b.Property<string>("TextoArchivo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PsicologoId");

                    b.ToTable("instrumentos", (string)null);
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.IntegranteHogarEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExpedienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("text");

                    b.Property<string>("Parentesco")
                        .HasColumnType("text");

                    b.Property<string>("StatusRelacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("integrantes_hogar", (string)null);
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.MedicamentoDelExpedienteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Dosis")
                        .HasColumnType("text");

                    b.Property<long>("ExpedienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Frecuencia")
                        .HasColumnType("text");

                    b.Property<long>("MedicamentoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("medicamentos_expediente", (string)null);
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.MedicamentoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.PacienteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("text");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("text");

                    b.Property<string>("Escolaridad")
                        .HasColumnType("text");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("TelefonoEmergencia")
                        .HasColumnType("text");

                    b.Property<string>("TipoVivienda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.ProblemaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("AfectacionAmigos")
                        .HasColumnType("smallint");

                    b.Property<byte>("AfectacionEconomico")
                        .HasColumnType("smallint");

                    b.Property<byte>("AfectacionEspiritual")
                        .HasColumnType("smallint");

                    b.Property<byte>("AfectacionFamiliar")
                        .HasColumnType("smallint");

                    b.Property<byte>("AfectacionLaboral")
                        .HasColumnType("smallint");

                    b.Property<byte>("AfectacionPareja")
                        .HasColumnType("smallint");

                    b.Property<byte>("AfectacionSalud")
                        .HasColumnType("smallint");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Frecuencia")
                        .HasColumnType("text");

                    b.Property<int>("Intensidad")
                        .HasColumnType("integer");

                    b.Property<long>("SesionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SesionId");

                    b.ToTable("problemas", (string)null);
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.RespuestaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("RutaArchivo")
                        .HasColumnType("text");

                    b.Property<string>("Valoracion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("respuestas", (string)null);
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.SesionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ComentarioPsicologa")
                        .HasColumnType("text");

                    b.Property<long>("ExpedienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PsicologoId")
                        .HasColumnType("bigint");

                    b.Property<byte>("PuntuacionArregloPersonal")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionArticulacion")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionBienestar")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionCoherencia")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionContactoVisual")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionEspontaneidad")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionHabla")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionPostura")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionVelocidadHabla")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionVestimenta")
                        .HasColumnType("smallint");

                    b.Property<byte>("PuntuacionVolumenHabla")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.HasIndex("PsicologoId");

                    b.ToTable("sesiones", (string)null);
                });

            modelBuilder.Entity("pacientes_psicologos", b =>
                {
                    b.Property<long>("PacientesId")
                        .HasColumnType("bigint");

                    b.Property<long>("PsicologosId")
                        .HasColumnType("bigint");

                    b.HasKey("PacientesId", "PsicologosId");

                    b.HasIndex("PsicologosId");

                    b.ToTable("pacientes_psicologos");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.AdministradorEntity", b =>
                {
                    b.HasBaseType("backend_clinica.Persistence.Entities.EmpleadoEntity");

                    b.HasDiscriminator().HasValue("administrador");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.PsicologoEntity", b =>
                {
                    b.HasBaseType("backend_clinica.Persistence.Entities.EmpleadoEntity");

                    b.HasDiscriminator().HasValue("psicologo");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.RecepcionistaEntity", b =>
                {
                    b.HasBaseType("backend_clinica.Persistence.Entities.EmpleadoEntity");

                    b.HasDiscriminator().HasValue("recepcionista");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.CartaConcentimientoEntity", b =>
                {
                    b.HasOne("backend_clinica.Persistence.Entities.PacienteEntity", "Paciente")
                        .WithOne("Carta")
                        .HasForeignKey("backend_clinica.Persistence.Entities.CartaConcentimientoEntity", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.ComentarioSesionEntity", b =>
                {
                    b.HasOne("backend_clinica.Persistence.Entities.SesionEntity", "Sesion")
                        .WithMany("Comentarios")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.ExpedienteEntity", b =>
                {
                    b.HasOne("backend_clinica.Persistence.Entities.PacienteEntity", "Paciente")
                        .WithOne("Expediente")
                        .HasForeignKey("backend_clinica.Persistence.Entities.ExpedienteEntity", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.FamiliarConfianzaEntity", b =>
                {
                    b.HasOne("backend_clinica.Persistence.Entities.ExpedienteEntity", "Expediente")
                        .WithMany("FamiliaresConfianza")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.InstrumentoEntity", b =>
                {
                    b.HasOne("backend_clinica.Persistence.Entities.PsicologoEntity", "Psicologo")
                        .WithMany("Instrumentos")
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.IntegranteHogarEntity", b =>
                {
                    b.HasOne("backend_clinica.Persistence.Entities.ExpedienteEntity", "Expediente")
                        .WithMany("IntegrantesHogar")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.MedicamentoDelExpedienteEntity", b =>
                {
                    b.HasOne("backend_clinica.Persistence.Entities.ExpedienteEntity", "Expediente")
                        .WithMany("MedicamentosDelExpediente")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_clinica.Persistence.Entities.MedicamentoEntity", "Medicamento")
                        .WithMany("Expedientes")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.ProblemaEntity", b =>
                {
                    b.HasOne("backend_clinica.Persistence.Entities.SesionEntity", "Sesion")
                        .WithMany("Problemas")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.SesionEntity", b =>
                {
                    b.HasOne("backend_clinica.Persistence.Entities.ExpedienteEntity", "Expediente")
                        .WithMany("Sesiones")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_clinica.Persistence.Entities.PsicologoEntity", "Psicologo")
                        .WithMany("Sesiones")
                        .HasForeignKey("PsicologoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("Psicologo");
                });

            modelBuilder.Entity("pacientes_psicologos", b =>
                {
                    b.HasOne("backend_clinica.Persistence.Entities.PacienteEntity", null)
                        .WithMany()
                        .HasForeignKey("PacientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_clinica.Persistence.Entities.PsicologoEntity", null)
                        .WithMany()
                        .HasForeignKey("PsicologosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.ExpedienteEntity", b =>
                {
                    b.Navigation("FamiliaresConfianza");

                    b.Navigation("IntegrantesHogar");

                    b.Navigation("MedicamentosDelExpediente");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.MedicamentoEntity", b =>
                {
                    b.Navigation("Expedientes");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.PacienteEntity", b =>
                {
                    b.Navigation("Carta");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.SesionEntity", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Problemas");
                });

            modelBuilder.Entity("backend_clinica.Persistence.Entities.PsicologoEntity", b =>
                {
                    b.Navigation("Instrumentos");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
