using backend_clinica.Domain;
using backend_clinica.Persistence.Entities;

namespace backend_clinica.Persistence;

// Navigation properties are deliberately excluded; services attach relationships by foreign key.
public static class DomainEntityMapper
{
    public static PacienteEntity ToEntity(this Paciente source) => new() { Id = source.Id, Fecha = source.Fecha, TelefonoEmergencia = source.TelefonoEmergencia, Telefono = source.Telefono, Escolaridad = source.Escolaridad, Nombre = source.Nombre, ApellidoPaterno = source.ApellidoPaterno, ApellidoMaterno = source.ApellidoMaterno, EstadoCivil = source.EstadoCivil.ToString(), TipoVivienda = source.TipoVivienda.ToString() };
    public static Paciente ToDomain(this PacienteEntity source) => new() { Id = source.Id, Fecha = source.Fecha, TelefonoEmergencia = source.TelefonoEmergencia, Telefono = source.Telefono, Escolaridad = source.Escolaridad, Nombre = source.Nombre, ApellidoPaterno = source.ApellidoPaterno, ApellidoMaterno = source.ApellidoMaterno, EstadoCivil = Enum.Parse<EstadoCivil>(source.EstadoCivil), TipoVivienda = Enum.Parse<TipoVivienda>(source.TipoVivienda) };

    public static ExpedienteEntity ToEntity(this Expediente source) => new() { Id = source.Id, EnfermedadPrevia = source.EnfermedadPrevia, Diagnostico = source.Diagnostico, Antecedentes = source.Antecedentes, PreguntaMagica = source.PreguntaMagica, Deseo = source.Deseo, Medicamentos = source.Medicamentos, MotivoConsulta = source.MotivoConsulta };
    public static Expediente ToDomain(this ExpedienteEntity source) => new() { Id = source.Id, EnfermedadPrevia = source.EnfermedadPrevia, Diagnostico = source.Diagnostico, Antecedentes = source.Antecedentes, PreguntaMagica = source.PreguntaMagica, Deseo = source.Deseo, Medicamentos = source.Medicamentos, MotivoConsulta = source.MotivoConsulta };

    public static EmpleadoEntity ToEntity(this Empleado source) => new() { Id = source.Id, Usuario = source.Usuario, Contrasenia = source.Contrasenia, Estado = source.Estado };
    public static Empleado ToDomain(this EmpleadoEntity source) => new() { Id = source.Id, Usuario = source.Usuario, Contrasenia = source.Contrasenia, Estado = source.Estado };
    public static PsicologoEntity ToEntity(this Psicologo source) => new() { Id = source.Id, Usuario = source.Usuario, Contrasenia = source.Contrasenia, Estado = source.Estado };
    public static Psicologo ToDomain(this PsicologoEntity source) => new() { Id = source.Id, Usuario = source.Usuario, Contrasenia = source.Contrasenia, Estado = source.Estado };
    public static AdministradorEntity ToEntity(this Administrador source) => new() { Id = source.Id, Usuario = source.Usuario, Contrasenia = source.Contrasenia, Estado = source.Estado };
    public static Administrador ToDomain(this AdministradorEntity source) => new() { Id = source.Id, Usuario = source.Usuario, Contrasenia = source.Contrasenia, Estado = source.Estado };
    public static RecepcionistaEntity ToEntity(this Recepcionista source) => new() { Id = source.Id, Usuario = source.Usuario, Contrasenia = source.Contrasenia, Estado = source.Estado };
    public static Recepcionista ToDomain(this RecepcionistaEntity source) => new() { Id = source.Id, Usuario = source.Usuario, Contrasenia = source.Contrasenia, Estado = source.Estado };

    public static SesionEntity ToEntity(this Sesion source) => new() { Id = source.Id, Fecha = source.Fecha, PuntuacionVestimenta = source.PuntuacionVestimenta, PuntuacionBienestar = source.PuntuacionBienestar, PuntuacionArregloPersonal = source.PuntuacionArregloPersonal, PuntuacionPostura = source.PuntuacionPostura, PuntuacionContactoVisual = source.PuntuacionContactoVisual, PuntuacionHabla = source.PuntuacionHabla, PuntuacionVelocidadHabla = source.PuntuacionVelocidadHabla, PuntuacionVolumenHabla = source.PuntuacionVolumenHabla, PuntuacionArticulacion = source.PuntuacionArticulacion, PuntuacionCoherencia = source.PuntuacionCoherencia, PuntuacionEspontaneidad = source.PuntuacionEspontaneidad, ComentarioPsicologa = source.ComentarioPsicologa };
    public static Sesion ToDomain(this SesionEntity source) => new() { Id = source.Id, Fecha = source.Fecha, PuntuacionVestimenta = source.PuntuacionVestimenta, PuntuacionBienestar = source.PuntuacionBienestar, PuntuacionArregloPersonal = source.PuntuacionArregloPersonal, PuntuacionPostura = source.PuntuacionPostura, PuntuacionContactoVisual = source.PuntuacionContactoVisual, PuntuacionHabla = source.PuntuacionHabla, PuntuacionVelocidadHabla = source.PuntuacionVelocidadHabla, PuntuacionVolumenHabla = source.PuntuacionVolumenHabla, PuntuacionArticulacion = source.PuntuacionArticulacion, PuntuacionCoherencia = source.PuntuacionCoherencia, PuntuacionEspontaneidad = source.PuntuacionEspontaneidad, ComentarioPsicologa = source.ComentarioPsicologa };

    public static ComentarioSesionEntity ToEntity(this ComentarioSesion source) => new() { Id = source.Id, NumeroSesion = source.NumeroSesion, ValoracionFin = source.ValoracionFin, ValoracionInicio = source.ValoracionInicio, AspectoAMedir = source.AspectoAMedir };
    public static ComentarioSesion ToDomain(this ComentarioSesionEntity source) => new() { Id = source.Id, NumeroSesion = source.NumeroSesion, ValoracionFin = source.ValoracionFin, ValoracionInicio = source.ValoracionInicio, AspectoAMedir = source.AspectoAMedir };
    public static ProblemaEntity ToEntity(this Problema source) => new() { Id = source.Id, Descripcion = source.Descripcion, Intensidad = source.Intensidad, Frecuencia = source.Frecuencia, AfectacionFamiliar = source.AfectacionFamiliar, AfectacionSalud = source.AfectacionSalud, AfectacionPareja = source.AfectacionPareja, AfectacionAmigos = source.AfectacionAmigos, AfectacionLaboral = source.AfectacionLaboral, AfectacionEspiritual = source.AfectacionEspiritual, AfectacionEconomico = source.AfectacionEconomico };
    public static Problema ToDomain(this ProblemaEntity source) => new() { Id = source.Id, Descripcion = source.Descripcion, Intensidad = source.Intensidad, Frecuencia = source.Frecuencia, AfectacionFamiliar = source.AfectacionFamiliar, AfectacionSalud = source.AfectacionSalud, AfectacionPareja = source.AfectacionPareja, AfectacionAmigos = source.AfectacionAmigos, AfectacionLaboral = source.AfectacionLaboral, AfectacionEspiritual = source.AfectacionEspiritual, AfectacionEconomico = source.AfectacionEconomico };
    public static IntegranteHogarEntity ToEntity(this IntegranteHogar source) => new() { Id = source.Id, Ocupacion = source.Ocupacion, Nombre = source.Nombre, StatusRelacion = source.StatusRelacion, FechaNacimiento = source.FechaNacimiento, Parentesco = source.Parentesco };
    public static IntegranteHogar ToDomain(this IntegranteHogarEntity source) => new() { Id = source.Id, Ocupacion = source.Ocupacion, Nombre = source.Nombre, StatusRelacion = source.StatusRelacion, FechaNacimiento = source.FechaNacimiento, Parentesco = source.Parentesco };
    public static FamiliarConfianzaEntity ToEntity(this FamiliarConfianza source) => new() { Id = source.Id, Nombre = source.Nombre, Parentesco = source.Parentesco, Telefono = source.Telefono };
    public static FamiliarConfianza ToDomain(this FamiliarConfianzaEntity source) => new() { Id = source.Id, Nombre = source.Nombre, Parentesco = source.Parentesco, Telefono = source.Telefono };
    public static MedicamentoEntity ToEntity(this Medicamento source) => new() { Id = source.Id, Nombre = source.Nombre, Descripcion = source.Descripcion };
    public static Medicamento ToDomain(this MedicamentoEntity source) => new() { Id = source.Id, Nombre = source.Nombre, Descripcion = source.Descripcion };
    public static MedicamentoDelExpedienteEntity ToEntity(this MedicamentoDelExpediente source) => new() { Id = source.Id as long? ?? 0, Dosis = source.Dosis, Frecuencia = source.Frecuencia };
    public static MedicamentoDelExpediente ToDomain(this MedicamentoDelExpedienteEntity source) => new() { Id = source.Id, Dosis = source.Dosis, Frecuencia = source.Frecuencia };
    public static CartaConcentimientoEntity ToEntity(this CartaConcentimiento source) => new() { Id = source.Id, RutaArchivo = source.RutaArchivo };
    public static CartaConcentimiento ToDomain(this CartaConcentimientoEntity source) => new() { Id = source.Id, RutaArchivo = source.RutaArchivo };
    public static InstrumentoEntity ToEntity(this Instrumento source) => new() { Id = source.Id, NombreInstrumento = source.NombreInstrumento, RutaArchivo = source.RutaArchivo, TextoArchivo = source.TextoArchivo };
    public static Instrumento ToDomain(this InstrumentoEntity source) => new() { Id = source.Id, NombreInstrumento = source.NombreInstrumento, RutaArchivo = source.RutaArchivo, TextoArchivo = source.TextoArchivo };
    public static RespuestaEntity ToEntity(this Respuesta source) => new() { Id = source.Id as long? ?? 0, Valoracion = source.Valoracion, RutaArchivo = source.RutaArchivo };
    public static Respuesta ToDomain(this RespuestaEntity source) => new() { Id = source.Id, Valoracion = source.Valoracion, RutaArchivo = source.RutaArchivo };
    public static Examen1Entity ToEntity(this Examen1 source) => new() { PuntuacionVestimenta = source.PuntuacionVestimenta, PuntuacionBienestar = source.PuntuacionBienestar, PuntuacionArregloPersonal = source.PuntuacionArregloPersonal, PuntuacionPostura = source.PuntuacionPostura, PuntuacionContactoVisual = source.PuntuacionContactoVisual, PuntuacionHabla = source.PuntuacionHabla, PuntuacionVelocidadHabla = source.PuntuacionVelocidadHabla, PuntuacionVolumenHabla = source.PuntuacionVolumenHabla, PuntuacionArticulacion = source.PuntuacionArticulacion, PuntuacionCoherencia = source.PuntuacionCoherencia, PuntuacionEspontaneidad = source.PuntuacionEspontaneidad };
    public static Examen1 ToDomain(this Examen1Entity source) => new() { PuntuacionVestimenta = source.PuntuacionVestimenta, PuntuacionBienestar = source.PuntuacionBienestar, PuntuacionArregloPersonal = source.PuntuacionArregloPersonal, PuntuacionPostura = source.PuntuacionPostura, PuntuacionContactoVisual = source.PuntuacionContactoVisual, PuntuacionHabla = source.PuntuacionHabla, PuntuacionVelocidadHabla = source.PuntuacionVelocidadHabla, PuntuacionVolumenHabla = source.PuntuacionVolumenHabla, PuntuacionArticulacion = source.PuntuacionArticulacion, PuntuacionCoherencia = source.PuntuacionCoherencia, PuntuacionEspontaneidad = source.PuntuacionEspontaneidad };
    public static ComentarioEntity ToEntity(this Comentario source) => new();
    public static Comentario ToDomain(this ComentarioEntity source) => new();
}
